[package]
name = "aws-nomad-spark-autoscaler"
version = "0.1.0"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.86"
reqwest = "0.9.9"
envy = "0.3.3"
serde_derive = "1.0.86"
serde_json = "1.0.38"
